swagger: '2.0'
info:
  version: v1
  title: REST API Documentation for the NRS TFRS Credit Trading Application
  description: The Transportation Fuels Reporting System is being designed to streamline compliance reporting for transportation fuel suppliers in accordance with the Renewable & Low Carbon Fuel Requirements Regulation.
  termsOfService: N/A
basePath: /api
paths:
